
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package Haskell;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int decc = 3;
  public static final int mod = 7;
  public static final int igualDoble = 39;
  public static final int dosPuntos = 36;
  public static final int corcheteC = 33;
  public static final int par = 60;
  public static final int corcheteA = 32;
  public static final int asc = 45;
  public static final int coma = 18;
  public static final int entonces = 62;
  public static final int igual = 15;
  public static final int dollar = 8;
  public static final int calcular = 43;
  public static final int caracter = 47;
  public static final int let = 42;
  public static final int succ = 2;
  public static final int menorIgual = 26;
  public static final int sum = 56;
  public static final int end = 41;
  public static final int si = 48;
  public static final int length = 61;
  public static final int salir = 55;
  public static final int mientras = 53;
  public static final int defecto = 52;
  public static final int numero = 10;
  public static final int interrumpir = 50;
  public static final int max = 63;
  public static final int menos = 20;
  public static final int menor = 24;
  public static final int porcentaje = 13;
  public static final int EOF = 0;
  public static final int lec = 4;
  public static final int mas = 19;
  public static final int revers = 58;
  public static final int para = 44;
  public static final int verdadero = 37;
  public static final int mayorIgual = 25;
  public static final int error = 1;
  public static final int mayor = 23;
  public static final int or = 28;
  public static final int pot = 5;
  public static final int por = 21;
  public static final int ERROR = 66;
  public static final int llaveC = 14;
  public static final int id = 9;
  public static final int puntoComa = 31;
  public static final int llaveA = 12;
  public static final int product = 57;
  public static final int falso = 38;
  public static final int sqrt = 6;
  public static final int caso = 51;
  public static final int impr = 59;
  public static final int hacer = 54;
  public static final int posicion = 35;
  public static final int desc = 46;
  public static final int disminuir = 34;
  public static final int diferente = 27;
  public static final int and = 29;
  public static final int not = 30;
  public static final int parentesisC = 17;
  public static final int parentesisA = 16;
  public static final int concatenar = 65;
  public static final int div = 22;
  public static final int min = 64;
  public static final int decimal = 40;
  public static final int sino = 49;
  public static final int cadena = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "succ",
  "decc",
  "lec",
  "pot",
  "sqrt",
  "mod",
  "dollar",
  "id",
  "numero",
  "cadena",
  "llaveA",
  "porcentaje",
  "llaveC",
  "igual",
  "parentesisA",
  "parentesisC",
  "coma",
  "mas",
  "menos",
  "por",
  "div",
  "mayor",
  "menor",
  "mayorIgual",
  "menorIgual",
  "diferente",
  "or",
  "and",
  "not",
  "puntoComa",
  "corcheteA",
  "corcheteC",
  "disminuir",
  "posicion",
  "dosPuntos",
  "verdadero",
  "falso",
  "igualDoble",
  "decimal",
  "end",
  "let",
  "calcular",
  "para",
  "asc",
  "desc",
  "caracter",
  "si",
  "sino",
  "interrumpir",
  "caso",
  "defecto",
  "mientras",
  "hacer",
  "salir",
  "sum",
  "product",
  "revers",
  "impr",
  "par",
  "length",
  "entonces",
  "max",
  "min",
  "concatenar",
  "ERROR"
  };
}

